def throw_exception(kind, msg):
    """
    Throws a Capacita exception and exits the program.
    """
    print(kind + ' exception')
    print(msg)
    exit()
